# Generated by Django 3.2.16 on 2023-01-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.IntegerField(auto_created=True, max_length=5, primary_key=True, serialize=False, verbose_name='编号')),
                ('weight', models.FloatField(max_length=5, null=True, verbose_name='羊肉重量（千克）')),
            ],
            options={
                'db_table': 'sheeps',
            },
        ),
    ]
