# Generated by Django 3.2.16 on 2023-01-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheeps', '0002_alter_sheep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='customer',
            field=models.CharField(max_length=16, null=True, verbose_name='顾客姓名'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='real_weight',
            field=models.FloatField(max_length=5, null=True, verbose_name='羊肉实际重量（千克）'),
        ),
    ]
