# Generated by Django 3.2.16 on 2023-01-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheeps', '0003_auto_20230108_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='memo',
            field=models.CharField(max_length=100, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='single_price',
            field=models.FloatField(max_length=8, null=True, verbose_name='单价 元/kg'),
        ),
        migrations.AddField(
            model_name='sheep',
            name='total_price',
            field=models.FloatField(max_length=8, null=True, verbose_name='总价 元'),
        ),
    ]
