# Generated by Django 3.2.16 on 2023-01-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheeps', '0004_auto_20230108_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='deal_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
