# Generated by Django 3.2.16 on 2023-01-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheeps', '0007_alter_sheep_deal_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheep',
            old_name='deal_time',
            new_name='deal_date',
        ),
    ]
